# Default values for acronyms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  hosts:
    - host: acronyms-127-0-0-1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - acronyms-127-0-0-1.nip.io
