---
image:
  repository: registry.localhost:5001/scruffaluff/acronyms
  tag: latest

ingress:
  className: ""
  enabled: true
  hosts:
    - host: acronyms.127-0-0-1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - acronyms.127-0-0-1.nip.io
