FROM node:18.1.0

RUN adduser --uid 1001 frontend
USER frontend

WORKDIR /repo

COPY --chown=frontend package*.json ./

RUN npm install

COPY . ./

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]
