FROM python:3.9.11

ENV POETRY_VIRTUALENVS_IN_PROJECT=1 PATH="/home/server/.local/bin:$PATH"

RUN adduser server

USER server

RUN pip install poetry

COPY --chown=server . /repo

WORKDIR /repo

RUN poetry install

EXPOSE 8000

ENTRYPOINT ["poetry", "run", "acronyms", "--reload", "--host", "0.0.0.0", "--port", "8000"]
