FROM python:3.9.11

ARG TARGETARCH

ENV POETRY_VIRTUALENVS_IN_PROJECT=1 PATH="/home/backend/.local/bin:$PATH"

RUN adduser backend

USER backend

RUN pip install poetry

COPY --chown=backend . /repo

WORKDIR /repo

RUN poetry install

# Set Bash as default shell.
SHELL ["/bin/bash", "-c"]

# Required on ARM images due to psycopg2-binary bug.
RUN if [[ "$TARGETARCH" == "arm64" ]]; then \
        poetry run pip uninstall psycopg2-binary; \
        poetry run pip install psycopg2==2.9.3; \
    fi

EXPOSE 8000

ENTRYPOINT ["poetry", "run", "acronyms", "--reload", "--host", "0.0.0.0", "--port", "8000"]
