---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    datree.skip/CONTAINERS_INCORRECT_READONLYROOTFILESYSTEM_VALUE: >-
      Rule is inaccurate for interpreted languages
  name: {{ include "acronyms.fullname" . }}
  labels:
    {{- include "acronyms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "acronyms.selectorLabels" . | nindent 6 }}
  template:
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "acronyms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "acronyms.fullname" . }}
          args:
            # Allows ingress controller to pass X-Forwarded headers.
            - --proxy-headers
          env:
            - name: ACRONYMS_RESET_TOKEN
              value: "{{ .Values.tokens.reset | default (randAlphaNum 64) }}"
            - name: ACRONYMS_SMTP_ENABLED
              value: "{{ .Values.smtp.enabled }}"
            - name: ACRONYMS_SMTP_HOST
              value: "{{ .Values.smtp.host }}"
            - name: ACRONYMS_SMTP_PASSWORD
              value: "{{ .Values.smtp.password }}"
            - name: ACRONYMS_SMTP_PORT
              value: "{{ .Values.smtp.port }}"
            - name: ACRONYMS_SMTP_TLS
              value: "{{ .Values.smtp.tls }}"
            - name: ACRONYMS_SMTP_USERNAME
              value: "{{ .Values.smtp.username }}"
            - name: ACRONYMS_VERIFICATION_TOKEN
              value: "{{ .Values.tokens.verification | default (randAlphaNum 64) }}"
            {{- if gt (len .Values.extraEnv) 0 }}
            {{- .Values.extraEnv | toYaml | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /api/acronym
              port: 8000
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/acronym
              port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        seccompProfile:
          type: RuntimeDefault
