"""Add description column

Revision ID: 46ee6e1569b5
Revises: 351b8c7d463b
Create Date: 2022-10-22 10:54:06.846022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46ee6e1569b5"
down_revision = "351b8c7d463b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("acronyms") as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.Unicode(), nullable=True)
        )
        batch_op.alter_column(
            "abbreviation", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.alter_column(
            "phrase", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.create_index(
            op.f("ix_acronyms_abbreviation"),
            ["abbreviation"],
            unique=False,
        )
        batch_op.create_index(
            op.f("ix_acronyms_phrase"), ["phrase"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_acronyms_phrase"), table_name="acronyms")
    op.drop_index(op.f("ix_acronyms_abbreviation"), table_name="acronyms")
    op.alter_column(
        "acronyms", "phrase", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "acronyms", "abbreviation", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("acronyms", "description")
    # ### end Alembic commands ###
